### ISSUE TITLE
百度云网盘挂了

### ISSUE THREAD

**Issue by naonaoaya** [printempw/live-stream-recorder#10]
百度云链接在20190711的下午分享被取消了。
麻烦请重新补档一下，感谢您的录播！

**Comment by Kafuziroh** [comment]
我这边看两个链接都还是正常的，请检查下是否位于百度云不支持的地区抑或是网络？

**Comment by naonaoaya** [comment]
可能是我自己的问题，在使用重庆、贵州、上海的均不能访问百度云。但是若开贵州的代理onedrive意外的快。十分感谢您的回复和一直以来录播。
祝好。
