### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by no-name2017** [printempw/live-stream-recorder#3]
我是从你的博客找到这里的，但是看到你的是linux的运行吗？我是windows的，感觉运行不了，不过我安装了streamlink的win版，请教下，如何保存直播的视频？谢谢。

**Comment by prinsss** [comment]
是的，这是 bash 脚本，Windows 下无法直接运行。如果你需要在 Windows 上使用，那么你可能需要安装 Cygwin 等 bash 环境（不保证可用）。

**Comment by prinsss** [comment]
由于长时间无人回复，我将关闭此 issue，如有问题欢迎继续留言。

**Comment by 1sm23** [comment]
链接对象已经开播，运行脚本还是not avaliable

**Comment by dsrkafuu** [comment]
我也遇到过这种问题，其中也分为好几种情况

- 第一次原因未知，更新完youtube-dl就正常了
- 第二次是油管出问题，录播群不少人没录到，直接获取/live 一直是 not avaliable；直接用直播地址（视频地址）就正常了

目前我个人只遇到过这些情况，具体还得问作者

**Comment by 1sm23** [comment]
谢谢回复，我打算录的链接是斗鱼，不知道会不会和你一样的原因
