### ISSUE TITLE
希望支持Pixiv sketch的直播，这个画师的直播都是默认没有历史观看的，只能自己存档

### ISSUE THREAD

**Issue by ZHONGRENsdfoidsjfiosdkfjdsoif** [printempw/live-stream-recorder#4]

**Comment by prinsss** [comment]
streamlink 之类的工具好像都不支持 Pixiv Sketch，得自己写解析，可惜的是我最近没什么时间。先说一个手动开始录像的方法吧：

打开画师直播间按 F12，切换至 Network 选项卡，找到以 `index.m3u8` 结尾的请求，把请求的完整 URL 复制下来，使用 `record_m3u8.sh` 脚本即可开始录像。举个例子：

```
./record_m3u8.sh "https://hlsa19.pixivsketch.net/2019012317/154823220710038971546e3b9126e7a1c110840b1e7066feb21/4000000_1920x1080/index.m3u8"
```

如果想要监控开播并自动录像，就得等我啥时候有时间写解析咯，抱歉。

**Comment by ZHONGRENsdfoidsjfiosdkfjdsoif** [comment]
streamlink 支持啊，这个工具早就有了pixiv sketch的录制插件

**Comment by dsrkafuu** [comment]
> @ZHONGRENsdfoidsjfiosdkfjdsoif streamlink 支持啊，这个工具早就有了pixiv sketch的录制插件

已验证 streamlink 支持 pixiv sketch
请使用 `./record_streamlink.sh https://sketch.pixiv.net/{@ID}/lives` 来进行自动监控与录制
例子: `./record_streamlink.sh https://sketch.pixiv.net/@0398asagi/lives` ([遠坂あさぎ](https://www.pixiv.net/member.php?id=3302692))
![](https://i.loli.net/2019/07/05/5d1f4882b5bff29024.png)

**Comment by prinsss** [comment]
Closing due to long period of inactivity. Feel free to reopen it if you still encounter this issue with the latest version! :)
