### ISSUE TITLE
似乎是使用不了了？

### ISSUE THREAD

**Issue by gitby2018** [printempw/live-stream-recorder#8]
尝试录制了一下斗鱼和twitch，都提示如下
“The stream is not available now.
Retry after 10 seconds...
”
是不是脚本已经失效了？
我尝试录制的都是正在直播的

**Comment by dsrkafuu** [comment]
已进行测试，Twitch正常，斗鱼暂时无效，需要检查一下
![](https://i.loli.net/2019/07/05/5d1f42ae025d244447.png)

**Comment by dsrkafuu** [comment]
Streamlink的斗鱼插件获取直播流地址返回401问题
请参考 https://github.com/streamlink/streamlink/issues/2328

**Comment by prinsss** [comment]
Closing due to long period of inactivity. Feel free to reopen it if you still encounter this issue with the latest version! :)
