### ISSUE TITLE
YouTube忽然更新导致所有现有录播工具损坏

### ISSUE THREAD

**Issue by wudifeixue** [printempw/live-stream-recorder#9]
# YouTube忽然更新导致所有现有录播工具损坏
## 目前已知的有：
本项目已经损坏，YouTube的所有录播均无法更新了。刚检查过OneDrive。  
猜测是Streamlink不行了，youtube-dl刚刚亲测还可以下载视频。  

除了YouTube以外，Twitcasting.tv还在正常工作，b站貌似也在工作（并没有亲自检查）。  
## 现在受到影响的项目有：
- 本项目
- [Auto Record Matsuri](https://github.com/fzxiao233/Auto_Record_Matsuri)

以及猜测所有这里的项目  
![image](https://user-images.githubusercontent.com/7316929/61036799-0b7a7d00-a387-11e9-9eef-0702f6a76c54.png)

**Comment by dsrkafuu** [comment]
https://github.com/kaguramea-record/live-stream-recorder/blob/master/record_youtube.sh
修修补补，仍在测试中，当前暂时可用

**Comment by Troogle** [comment]
看了下更新之后的脚本只是改了检测方式但是还是在使用streamlink, 根据昨天的测试streamlink在有些情况下还是坏的 streamlink/streamlink#2539

**Comment by dsrkafuu** [comment]
目前发现的几点问题以及可能解决方案：
1. `youtube-dl` 使用 `—match-filter is_live` 判断直播状态并监控失效
    - 使用 `wget -q -O- https://www.youtube.com/channel/$1/live|grep -q ‘‘\””sLive\\””true’` 进行检测
2. `streamlink` 在使用 `https://www.youtube.com/channel/[channel_id]/live` 无法获取地址 (https://github.com/streamlink/streamlink/issues/2541) (https://github.com/streamlink/streamlink/issues/2539)
    - 本原版 bash 并未受此影响, 其余受此影响的修改版本也可以先通过任意可行方法 (例如 `youtube-dl`) 获取视频 ID，再由 `streamlink` 通过 `https://www.youtube.com/watch?v=[video_id]` 进行获取与录制
3. `streamlink` 无法获取 1080p60 流 (https://github.com/streamlink/streamlink/issues/2539)
    - 未知，请参考 https://github.com/streamlink/streamlink/issues/2539 ，等待解决方案
4. `streamlink` 在使用 `https://www.youtube.com/watch?v=[video_id]` 依旧无法获取地址抑或是频繁中断
    - 请参考 https://github.com/streamlink/streamlink/issues/2537 和 https://github.com/streamlink/streamlink/issues/2539 ，若非此问题则未知或是向 `streamlink` 反馈
5. 待补充

**Comment by jitingcn** [comment]
streamlink 无法获取视频ID的问题我尝试做了一个修复 https://github.com/streamlink/streamlink/pull/2538
存在1080p60/720p60画质选项时仍可能出现问题，手动选择1080p/720p可以缓解

> Streamlink should not use MuxedStream for livestreams
同样是判断直播状态功能失效导致的

**Comment by jitingcn** [comment]
> https://github.com/kaguramea-record/live-stream-recorder/blob/master/record_youtube.sh
> 修修补补，仍在测试中，当前暂时可用

> 
	# Using wget to check the stream availability
    wget -q -O- https://www.youtube.com/channel/$1/live|grep -q '\\"isLive\\":true' && break

这种检测方式似乎并不靠谱，不管直播间是否开播都会返回 `"isLive":true`

**Comment by dsrkafuu** [comment]
> `wget -q -O- https://www.youtube.com/channel/$1/live|grep -q '\\"isLive\\":true' && break`
> 这种检测方式似乎并不靠谱，不管直播间是否开播都会返回 `"isLive":true`

我这边测试的几个频道都是正常的
这是使用wget获取的未开播的/live页面 https://paste.ubuntu.com/p/GPHBTrfP7Z/
这是使用wget获取的正在直播的/live页面 https://paste.ubuntu.com/p/s6rJzrXm3q/
使用 `"isLive":true` 匹配时正常

**Comment by dsrkafuu** [comment]
> 2. `streamlink` 在使用 `https://www.youtube.com/channel/[channel_id]/live` 无法获取地址 ([streamlink/streamlink#2541](https://github.com/streamlink/streamlink/issues/2541)) ([streamlink/streamlink#2539](https://github.com/streamlink/streamlink/issues/2539))
> 3. `streamlink` 无法获取 1080p60 流 ([streamlink/streamlink#2539](https://github.com/streamlink/streamlink/issues/2539))

2. 190712 13:54 通过ロボ子频道测试 `/live` 页面时 `streamlink` 已可正常获取
3. 190712 13:57 通过ロボ子频道测试 `streamlink` 依旧无法正常获取 1080p60/720p60 流，请参考前面 @jitingcn 提供的修复或是手动指定清晰度

**以之前发的使用 wget 的脚本为例，可以通过指定多个清晰度来避开 60 帧直播流**
`./record_youtube.sh "UCWCc8tO-uUl_7SJXIKJACMw" 1080p,720p,480p,360p loop 5`

**Comment by jitingcn** [comment]
> > `wget -q -O- https://www.youtube.com/channel/$1/live|grep -q '\\"isLive\\":true' && break`
> > 这种检测方式似乎并不靠谱，不管直播间是否开播都会返回 `"isLive":true`
> 
> 我这边测试的几个频道都是正常的
> 这是使用wget获取的未开播的/live页面 https://paste.ubuntu.com/p/GPHBTrfP7Z/
> 这是使用wget获取的正在直播的/live页面 https://paste.ubuntu.com/p/s6rJzrXm3q/
> 使用 `"isLive":true` 匹配时正常

抱歉，刚才没仔细检查，`\"isLive\":true` 的确可以正常匹配，但在 `'window["ytInitialData"]` 数据中也存在 `"isLive":true` ，不管是否开播。

**Comment by jitingcn** [comment]
> streamlink 无法获取视频ID的问题我尝试做了一个修复 streamlink/streamlink#2538
> 190712 13:54 通过ロボ子频道测试 /live 页面时 streamlink 已可正常获取
> 190712 13:57 通过ロボ子频道测试 streamlink 依旧无法正常获取 1080p60/720p60 流，请参考前面 @jitingcn 提供的修复或是手动指定清晰度

又检查了网站源码，YouTube 把 'window["ytInitialData"]' 的数据改回了原本的格式，我之前获取视频ID的修复方法已经失效了。

**Comment by Troogle** [comment]
```
URL=$(youtube-dl -g "$LIVE_URL" 2>/dev/null)
[[ -n "$URL" ]] && break
```
提供一个不用wget的检测思路 我这边是这么获取的

**Comment by jitingcn** [comment]
> > `wget -q -O- https://www.youtube.com/channel/$1/live|grep -q '\\"isLive\\":true' && break`
> > 这种检测方式似乎并不靠谱，不管直播间是否开播都会返回 `"isLive":true`
> 
> 我这边测试的几个频道都是正常的
> 这是使用wget获取的未开播的/live页面 https://paste.ubuntu.com/p/GPHBTrfP7Z/
> 这是使用wget获取的正在直播的/live页面 https://paste.ubuntu.com/p/s6rJzrXm3q/
> 使用 `"isLive":true` 匹配时正常

使用此方式也可以修复 streamlink 无法获取直播状态的问题 https://github.com/streamlink/streamlink/pull/2543

**Comment by jitingcn** [comment]
https://github.com/ytdl-org/youtube-dl/commit/27019dbb4b4829b5e1910c6b714f904ce8fad680
youtube-dl 已经修复了= =

**Comment by wudifeixue** [comment]
大佬们辛苦了，我看录播机已经正常工作，可以考虑关闭issue了？

**Comment by prinsss** [comment]
thanks everyone! ;)
